### ISSUE TITLE
System tests have bitrotted.

### ISSUE THREAD

**Issue by tseaver** [googleapis/google-resumable-media-python#67]
- [ ] Mangling `os.environ` in `tests/system/requests/test_download.py` is not 2.7-compatible. (PR #77)
- [ ] `tests/system/requests/test_download.test_corrupt_download` shows a mismash on the actual hash. (Issue #76, xfailed in PR #77)
- [ ] `test_chunked_download` is getting an all-in-one response (inital response has no `Location` header, payload in body). (Issue #56, xfailed in PR #77)
- ~~Default storage class is now `MULTI_REGIONAL`, not `STANDARD`, which breaks assertions in almost all the upload tests.~~ No longer true:  the default is `STANDARD` again.
- [ ] We need to set up the CI environment to run the system tests.(PR #77)

**Comment by tseaver** [comment]
The failure in `test_corrupt_download` occurs only for the gzipped file, which likely indicates that the test is exercising #50.
